config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :traders, only: [:create]
  # resources :traders, except: [:show, :index, :new, :update, :destroy, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trader.rb
class Trader < ApplicationRecord
  # after_create :send_welcome_email
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  private

  # def send_welcome_email
  #   TraderMailer.welcome(self).deliver_now
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @trader = Trader.new
  end
end

app/controllers/traders_controller.rb
class TradersController < ApplicationController
    skip_before_action :authenticate_user!

  def new
    @trader = Trader.new
  end

  def create
    # set_trader
    @trader = Trader.new(trader_params)
    if @trader.save
      redirect_to root_path, notice: "Congratulations! You've just subscribed to signals"
      # SendpulseJob.perform_now
    else
      redirect_to root_path, notice: "Something went wrong. Please enter your email again"
    end
  end

  private

  def set_trader
    @trader = Trader.find(params[:id])
  end

  def trader_params
    params.require(:trader).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Signals App | Get free trading signals</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">


  </head>
  <body>
    <%#= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class='banner slider'>
    <div class='banner slide1'></div>
    <div class='banner slide2'></div>
    <div class='banner slide3'></div>

     <div class="head-container">

    <h1>Trading Signals App</h1>
    <p>95% of traders fail. Join the top 5%</p>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4 col-md-4 offset-md-4">

      <div class="form-login">
        <%= simple_form_for @trader, url: traders_url, method: :post do |f| %>
          <%#= f.input :name, label: false, input_html: { class: "form-control form-control-lg", placeholder: "Enter your name" } %>
          <%#= f.input :phone, label: false, input_html: { class: "form-control form-control-lg", placeholder: "Enter your phone" } %>
          <%= f.input :email, label: false, input_html: { class: "form-control form-control-lg", placeholder: "Enter your email" } %>
          <%= f.submit 'Sign Up For Free Trading Signals', class: 'btn btn-danger' %>
        <% end %>
      </div>

  </div>
</div>

</div>
</div>
</div>

<div class="section" id="performance">
  <div class="container">
    <h2>Signals Performance</h2>
    <div class="row align-items-center">
      <div class="col-sm">
        <h3>Double-Digits Profitability</h3>
        <p>Our signal alerts are mostly based on pending orders and are sent to you few times a week. The system generates several signals, yet we only send signals which offer at least a 1:1 Risk Reward Ratio. We use stop losses of 30 - 100 pips and have pre-defined take profit levels. Occasionally, a take profit level will be changed to a trailing stop if the market makes a clear break through our target level.</p>
      </div>

      <div class="col-sm">
        <%= image_tag "chart.svg", alt: "chart", id: "chart" %>
      </div>
    </div>
  </div>
</div>





<div class="section" id="how-it-works">
  <div class="container">
    <h2>How It All Works</h2>
    <div class="row justify-content-between">
      <div class="col-sm"><i class="fas fa-user-plus fa-4x"></i><p>Sign Up</p></div>
      <div class="col-sm"><i class="fas fa-envelope-open fa-4x"></i><p>Get Signals</p></div>
      <div class="col-sm"><i class="fas fa-money-check-alt fa-4x"></i><p>Trade & Profit</p></div>
    </div>
  </div>
</div>


<div class="section" id="who-we-are">
  <div class="container">
    <h2>Who We Are</h2>
    <div class="row justify-content-between">
      <div class="col-sm">
        <%= image_tag "benjamin_hirsch.jpg", alt: "photo", id: "we-photo" %>
        <h3>Benjamin Hirsch</h3>
        <h4>CEO, 59</h4>
        <p>CEO for 1 year, previous experience of over 30 years within the banking industry</p>
      </div>
      <div class="col-sm">
        <%= image_tag "pietro_danielo.jpg", alt: "photo", id: "we-photo" %>
        <h3>Pietro Danielo</h3>
        <h4>Head Developer, 45</h4>
        <p>Lead developer for Euro hedge fund for 10 years, Master’s degree in mathematics</p>
      </div>
      <div class="col-sm">
        <%= image_tag "ailsa_waithe.jpg", alt: "photo", id: "we-photo" %>
        <h3>Ailsa Waithe</h3>
        <h4>Senior Researcher, 37</h4>
        <p>Former researcher of world economics. Bachelor in Finance with honors and Master in Math</p>
      </div>
      <div class="col-sm">
        <%= image_tag "jeff_keith.jpg", alt: "photo", id: "we-photo" %>
        <h3>Jeff Keith</h3>
        <h4>Customer Relations Manager, 40</h4>
        <p>Over 10 years of experience working within financial call centers, degree in Economics</p>
      </div>
    </div>

  </div>
</div>


<!-- <div class="section" id="testimonials">
  <div class="container">
    <h2>Testimonials</h2>
    <div class="row">
      <div class="left"></div>
      <div class="right"></div>
    </div>
  </div>
</div> -->


<div class="section" id="reg-form">
  <div class="container">
    <h2>Register Now</h2>
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-4 col-md-4 offset-md-4">

        <div class="form-login">
        <%= simple_form_for @trader, url: traders_url, method: :post do |f| %>
          <%#= f.input :name, label: false, input_html: { class: "form-control form-control-lg", placeholder: "Enter your name" } %>
          <%#= f.input :phone, label: false, input_html: { class: "form-control form-control-lg", placeholder: "Enter your phone" } %>
          <%= f.input :email, label: false, input_html: { class: "form-control form-control-lg", placeholder: "Enter your email" } %>
          <%= f.submit 'Sign Up For Free Trading Signals', class: 'btn btn-danger' %>
        <% end %>
        </div>

    </div>
</div>

</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#">Privacy Policy</a>
    <a href="#">Terms and Conditions</a>
    <a href="#">Cookies Policy</a>
    <a href="#">Risk Disclaimer</i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-dollar-sign"></i> in mind
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <!-- <h1>Trading Signals App</h1> -->
    <%#= image_tag "m-b-m-795202-unsplash.jpg", class: 'rounded' %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
       <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Signals Performance", "/", class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Registration", "/", class: "nav-link" %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>